features:
  - name: 'aatype'
    pad_type: 'seq'
  - name: 'residue_index'
    pad_type: 'seq'
  - name: 'all_atom_positions'
    pad_type: 'seq'
  - name: 'all_atom_mask'
    pad_type: 'seq'
  - name: 'resolution'
    pad_type: 'seq'
    meta_data: True
  - name: 'is_distillation'
    pad_type: 'seq'
    meta_data: True
  - name: 'atom14_atom_exists'
    pad_type: 'seq'
  - name: 'residx_atom14_to_atom37'
    pad_type: 'seq'
  - name: 'residx_atom37_to_atom14'
    pad_type: 'seq'
  - name: 'atom37_atom_exists'
    pad_type: 'seq'
  - name: 'atom14_gt_exists'
    pad_type: 'seq'
  - name: 'atom14_gt_positions'
    pad_type: 'seq'
  - name: 'atom14_alt_gt_positions'
    pad_type: 'seq'
  - name: 'atom14_alt_gt_exists'
    pad_type: 'seq'
  - name: 'rigidgroups_gt_frames'
    pad_type: 'seq'
  - name: 'rigidgroups_gt_exists'
    pad_type: 'seq'
  - name: 'rigidgroups_group_exists'
    pad_type: 'seq'
  - name: 'rigidgroups_group_is_ambiguous'
    pad_type: 'seq'
  - name: 'rigidgroups_alt_gt_frames'
    pad_type: 'seq'
  - name: 'torsion_angles_sin_cos'
    pad_type: 'seq'
  - name: 'alt_torsion_angles_sin_cos'
    pad_type: 'seq'
  - name: 'torsion_angles_mask'
    pad_type: 'seq'
  - name: 'pseudo_beta'
    pad_type: 'seq'
  - name: 'pseudo_beta_mask'
    pad_type: 'seq'
  - name: 'backbone_rigid_tensor'
    pad_type: 'seq'
  - name: 'backbone_rigid_mask'
    pad_type: 'seq'
  - name: 'chi_angles_sin_cos'
    pad_type: 'seq'
  - name: 'chi_mask'
    pad_type: 'seq'
  - name: 'sequence'
    pad_type: 'esm'
  - name: 'distance_mat_stack'
    pad_type: 'seq'
    pair_type: True

  

  
  

  
  